export const WORDS = [
  'REACT', 'NATIVO', 'EXPO', 'JAVASCRIPT', 'ANDROID', 'IOS', 'COMPONENTE',
  'ESTADO', 'PROPRIEDADE', 'FUNCAO', 'HOOK', 'PROMESSE', 'ASSINCRONO',
  'ALGORITMO', 'VARIAVEL', 'OBJETO', 'ARRAY', 'MATRIZ', 'DESENVOLVIMENTO',
  'MOBILE', 'INTERFACE', 'ESTILOS', 'LAYOUT', 'NAVEGACAO', 'APLICACAO',
  'PERFORMANCE', 'REUTILIZAVEL', 'RESPONSIVO', 'TESTES', 'DEPLOY', 'GITHUB',
  'COMPILAR', 'TRANSPILE', 'PACKAGER', 'BUNDLER', 'CONSOLE', 'ERRO', 'DEBUG'
];
